<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>AuctionResponse.Ui</AssemblyName>
    <RootNamespace>AuctionResponse.Ui</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AuctionResponse.Core\AuctionResponse.Core.csproj" />
  </ItemGroup>
</Project>
